const PRODUCT_LIST_REQUESTED = 'PRODUCT_LIST_REQUESTED';
const PRODUCT_LIST_SUCCEED = 'PRODUCT_LIST_SUCCEED';
const PRODUCT_LIST_FAILED = 'PRODUCT_LIST_FAILED';
const SEARCH_PRODUCT_REQUESTED = "SEARCH_PRODUCT_REQUESTED";
const SEARCH_PRODUCT_SUCCEED = "SEARCH_PRODUCT_SUCCEED";
const SEARCH_PRODUCT_FAILED = "SEARCH_PRODUCT_FAILED";

export {
    PRODUCT_LIST_REQUESTED,
    PRODUCT_LIST_FAILED,
    PRODUCT_LIST_SUCCEED,

    SEARCH_PRODUCT_REQUESTED,
    SEARCH_PRODUCT_SUCCEED,
    SEARCH_PRODUCT_FAILED
}