const PRODUCT_LIST_REQUESTED = 'PRODUCT_LIST_REQUESTED';
const PRODUCT_LIST_SUCCEED = 'PRODUCT_LIST_SUCCEED';
const PRODUCT_LIST_FAILED = 'PRODUCT_LIST_FAILED';

export {
    PRODUCT_LIST_REQUESTED,
    PRODUCT_LIST_FAILED,
    PRODUCT_LIST_SUCCEED
}