const PRODUCT_LIST_REQUESTED = 'PRODUCT_LIST_REQUESTED';
const PRODUCT_LIST_SUCCEED = 'PRODUCT_LIST_SUCCEED';
const PRODUCT_LIST_FAILED = 'PRODUCT_LIST_FAILED';
const SEARCH_PRODUCT_REQUESTED = "SEARCH_PRODUCT_REQUESTED";
const SEARCH_PRODUCT_SUCCEED = "SEARCH_PRODUCT_SUCCEED";
const SEARCH_PRODUCT_FAILED = "SEARCH_PRODUCT_FAILED";

const PRODUCT_SUBTRACT_STOCK = "PRODUCT_SUBTRACT_STOCK";
const ADD_NEW_ITEM = "ADD_NEW_ITEM";
const REMOVE_ITEM_FROM_STOCK = "REMOVE_ITEM_FROM_STOCK";
const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";

export {
    PRODUCT_LIST_REQUESTED,
    PRODUCT_LIST_FAILED,
    PRODUCT_LIST_SUCCEED,

    SEARCH_PRODUCT_REQUESTED,
    SEARCH_PRODUCT_SUCCEED,
    SEARCH_PRODUCT_FAILED,

    PRODUCT_SUBTRACT_STOCK,
    ADD_NEW_ITEM,
    REMOVE_ITEM_FROM_STOCK,
    ADD_ITEM_TO_CART
}